### ISSUE TITLE
Calculator doesn't work properly

### ISSUE THREAD

**Issue by vishalps2606** [vishalps2606/DesktopCalculator#1]
The DesktopCalculator application doesn't work properly as it fluctuates results on different inputs.

**Comment by devmaaj** [comment]
Greetings, 

is this issue still open? Could I colaborate?
If yes, please assign me

**Comment by vishalps2606** [comment]
yes, it is still open!
and I have assigned it to you.
Go Ahead.

And please write the error solution whether in Readme or in the reply of this comment.

**Comment by devmaaj** [comment]
<a href="https://github.com/vishalps2606/DesktopCalculator/pull/2">Pull Resquest here</a>

When choicebox is loaded and default value "ADD" is added to choicebox value props nothing happens to validate this value and it is causing a invalid calculate method call because there is no choicebox value recognized until you do that for the first time.

I've deleted the choicebox listener because it cannot validate default value and move the validation to inside of calculate method getting the choicebox value props directly

**Comment by vishalps2606** [comment]
Issue resolved!
